DROP TABLE IF EXISTS Story_updates;
DROP TABLE IF EXISTS Votes;
DROP TABLE IF EXISTS Options;
DROP TABLE IF EXISTS Questions;
DROP TABLE IF EXISTS Writings;
DROP TABLE IF EXISTS Chapters;
DROP TABLE IF EXISTS Banned_users;
DROP TABLE IF EXISTS Tokens;
DROP TABLE IF EXISTS Users;

DROP TYPE IF EXISTS question_type;
DROP TYPE IF EXISTS user_type;
